### ISSUE TITLE
bug: incorrect example

### ISSUE THREAD

**Issue by modernNeo** [sapphiredev/website#177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

The [examples for creating a `PreCondition` class](https://www.sapphirejs.dev/docs/Guide/preconditions/creating-your-own-preconditions#creating-a-precondition-class) is not valid

The `Config` object reference at line `Config.bot.owners!.includes(userId)` has not been delcared.

### Steps To Reproduce

NA

### Expected behavior

NA

**Comment by favna** [comment]
This was answered in the Discord server:

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/4019718/172456320-2a5e1e6e-966b-49b1-8d86-0249db04c68f.png">

**Comment by modernNeo** [comment]
@favna is the intended audience of the examples a newbie to TS and front-end programming languages or an intermediate user of TS?

**Comment by favna** [comment]
Honestly, I have no idea how to answer that, I'm sorry. On the one side, you make a good argument, but on the other side Discord bot development, in general, isn't really the best starting point for fresh new developers in my opinion.

**Comment by modernNeo** [comment]
@favna I respectfully disagree.

If y'all don't intend your documentation to be something that can spoon-feed instructions to newbie JS/TS devs like myself, that is your perogative and totally fair.

But https://github.com/Rapptz/discord.py proved that it is possible to create documentation that can allow newbies to learn discord **and** python and create a discord bot while someone is at it. if discord.py's documentation was not as extensive as it is, I would not be the OS dev I am 😄
