### ISSUE TITLE
request: mention `loadMessageCommandListeners` to the getting started page

### ISSUE THREAD

**Issue by devramsean0** [sapphiredev/website#207]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

Add a mention of how to load message commands, this has come to mind after I saw a message in #sapphire-support asking for help

### Desired solution

add an info element containing something like:
`If you want to use message commands. Set LoadMessageCommandListeners to true in your client options`

### Alternatives considered

N/A

### Additional context

I am intending to submit a PR for this during hacktoberfest, only opening an issue for tracking purposes

**Comment by anvikshaaa24** [comment]
Please guide on what has to be done here

**Comment by devramsean0** [comment]
not much really, i just opened this to let the devs know a pr is incoming

**Comment by favna** [comment]
This has since been added, closing the issue.
