### ISSUE TITLE
request: Describe the usage of package.json in Getting Started

### ISSUE THREAD

**Issue by HavenSelph** [sapphiredev/website#260]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

The getting started documentation should CLEARLY state that the projects `package.json` `main` field must be set correctly to ensure files are imported at runtime. I spent quite a bit of time searching the docs, and help request to find that on typescript I must set my main to my output directory.

### Desired solution

Specify some sort of "Info" block that states the usage of this field.

### Alternatives considered

I really don't think there are alternatives, documentation is quite clear cut.

**Comment by favna** [comment]
Surely this is a joke?

![image](https://github.com/sapphiredev/website/assets/4019718/686d7e36-b410-4eeb-8118-a34f257c150f)

**Comment by favna** [comment]
Closing due to lack of author response
